[package]
name = "accneat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#accneat-bin = { path = "../accneat-bin" }
whiteread = "0.5"

[dev-dependencies]
serial_test = "*"
